<?php if (($_productCollection = $this->getProductCollection()) && $_productCollection->getSize()): ?>
    <?php
    $_columnCount = $this->getColumnCount();
    $theme=Mage::helper('welldone');
    $theme_ajax=Mage::helper('ajaxaddto');
    $_helper = $this->helper('catalog/output');
    $image_width=263;
    $image_height=330;
    if($theme->getConfigOption('general/site_width')==2 || $theme->getConfigOption('general/site_width')==3)
    {
        $image_width=349;
        $image_height=438;
    }
    $cols='four-in-row';
    if($_columnCount==3)
    {
        $cols='three-in-row';
        $image_width=360;
        $image_height=451;
    }
    if($_columnCount==5)
    {
        $cols='five-in-row';
        $image_width=204;
        $image_height=255;
    }
    if(count($_productCollection)):
        ?>
        <section class="content">
            <div class="container">
                <h2 class="text-center text-uppercase"><?php echo $this->getBlockName();?></h2>
                <div class="row product-carousel mobile-special-arrows animated-arrows product-grid <?php echo $cols?>">
                    <?php foreach ($_productCollection as $_product): ?>
                        <?php // if(!$_product->isSaleable() && !Mage::getStoreConfig('cataloginventory/options/show_out_of_stock'))continue; ?>
                        <div class="product-preview-wrapper">
                            <div class="product-preview">

                                <div class="product-preview__image">
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                        <img id ="product-collection-image-<?php echo $_product->getId(); ?>"  src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($image_width,$image_height); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" data-image2x="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($image_width*2,$image_height*2); ?>"/>
                                    </a>
                                    <?php echo $theme->countdownSpecialPrice($_product,'defaultCountdown',$this)?>
                                    <?php if(!$_product->isSaleable()): ?>
                                        <div class="product-preview__outstock"><?php echo $this->__('Out of stock') ?></div>
                                    <?php endif; ?>
                                </div>

                                <?php echo $theme->getProductLabel($_product,$this)?>

                                <div class="product-preview__info text-center">
                                    <?php if($_product->isSaleable()): ?>
                                        <div class="product-preview__info__btns">
                                            <?php  echo $theme_ajax->addToCartLink('<a href="#" class="btn btn--round add-to-cart-btn-'.$_product->getId().'"><span class="icon-ecommerce"></span></a> ',$_product,$this);?>
                                            <?php echo $theme->quickViewLink('<a href="#" class="btn btn--round btn--dark btn-quickview" data-toggle="modal" data-target="#quickView"><span class="icon icon-eye"></span></a>',$_product,$this);?>
                                        </div>
                                    <?php endif; ?>
                                    <div class="product-preview__info__title">
                                        <h2><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                                    </div>
                                    <div class="rating"><?php  echo $theme->ratingStars('<span class="icon-star"></span>','',$_product,$this);?></div>
                                    <?php
                                    if (Mage::getStoreConfig('configswatches/general/enabled', Mage::app()->getStore())) {
                                        echo $this->getLayout()->createBlock('core/template')->setTemplate('configurableswatches/catalog/product/list/swatches.phtml')->setProduct($_product)->toHtml();
                                    }
                                    ?>
                                    <?php echo $this->getPriceHtml($_product, true) ?>
                                    <div class="product-preview__info__link">
                                        <?php  echo $theme_ajax->compareLink('<a href="#"><span class="icon icon-bars"></span><span class="product-preview__info__link__text">'.$this->__('Add to compare').'</span></a>',$_product,$this);?>
                                        <?php  echo $theme_ajax->wishlistLink('<a href="#"><span class="icon icon-favorite"></span><span class="product-preview__info__link__text">'.$this->__('Add to wishlist').'</span></a>',$_product,$this);?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
        </section>

        <?php
        if (Mage::getStoreConfig('configswatches/general/enabled', Mage::app()->getStore())) {
            echo $this->getLayout()->createBlock('configurableswatches/catalog_media_js_list')->setTemplate('configurableswatches/catalog/media/js.phtml')->setProductCollection($_productCollection)->toHtml();
        }
        ?>
    <?php endif; ?>
<?php endif; ?>