<?php if ($_productCollection=$this->getLoadedProductCollection()): ?>
    <?php
    $theme=Mage::helper('welldone');
    $theme_ajax=Mage::helper('ajaxaddto');
    $_helper = $this->helper('catalog/output');
    $image_width=566;
    $image_height=710;
    $double_products=explode(',',$this->getBlockName());
    if(count($_productCollection)):
    ?>
        <div class="chapter__title title--dark text-center">
            <div class="chapter__title__text">
                <h2 class="text-uppercase"><?php echo $this->getBlockName();?></h2>
            </div>
        </div>
        <div class="chapter__content">
            <?php foreach ($_productCollection as $_product): ?>
            <div class="art-catalogue__item art-catalogue__item--full">
                <div class="product-preview-wrapper">
                    <div class="product-preview">
                        <div class="product-preview__image">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                                <img  src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($image_width,$image_height); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" data-image2x="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($image_width*2,$image_height*2); ?>"/>
                            </a>
                        </div>
                        <?php echo $theme->getProductLabel($_product,$this)?>
                        <div class="product-preview__info text-center">
                            <div class="product-preview__info__more"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="btn btn--round"><span><?php echo $this->__('View<br/>More') ?></span></a></div>
                            <div class="product-preview__info__title">
                                <h2><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php endforeach ?>
        </div>
    <?php endif; ?>
<?php endif; ?>