<?php if (($_productCollection = $this->getProductCollection()) && $_productCollection->getSize()): ?>
    <?php
    $_helper = $this->helper('catalog/output');
    $theme=Mage::helper('welldone');
    $image_width=74;
    $image_height=92;
    ?>
    <h4 class="text-uppercase"><?php echo $this->getBlockName();?></h4>
    <div class="products-widget card">
        <div class="products-widget-carousel nav-dot">
            <?php foreach ($_productCollection as $_product): ?>
                <?php //  if(!$_product->isSaleable() && !Mage::getStoreConfig('cataloginventory/options/show_out_of_stock'))continue; ?>
                <div class="products-widget__item">
                    <div class="products-widget__item__image pull-left">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                            <img   src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($image_width,$image_height); ?>"  alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" data-image2x="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($image_width*2,$image_height*2); ?>"/>
                        </a>
                    </div>
                    <div class="products-widget__item__info">
                        <div class="products-widget__item__info__title">
                            <h2 class="text-uppercase"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                        </div>
                        <div class="rating"><span class="icon-star"></span><span class="icon-star"></span><span class="icon-star"></span><span class="icon-star"></span><span class="icon-star"></span></div>
                        <?php echo $this->getPriceHtml($_product, true) ?>
                    </div>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>