<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php
$name=$this->__('Name:');
$email=$this->__('E-Mail:');
$comment=$this->__('Comment');
$url=$this->__('Website:');
?>
<br /><br />
<form id="respond" method="post" action="<?php echo $this->getCommentFormAction() ?>"  class="contact-form">
    <div class="display-none">
        <input type="hidden" name="comment_post_ID" value="<?php echo $this->getPostId() ?>"/>
        <input type="hidden" name="comment_parent" id="comment_parent" value="<?php echo (int)$this->getRequest()->getParam('replytocom', 0) ?>"/>
    </div>
    <div class="fieldset">





        <?php if ($this->customerMustLogin()): ?>
            <p><?php echo $this->__('Sorry, you must be logged in to post a comment.') ?></p>
            <p><button class="button btn-login" type="button" onclick="setLocation('<?php echo $this->getLoginLink() ?>');"><span><span><?php echo $this->__('Login') ?></span></span></button></p>
        <?php else: ?>




                <?php if (!$this->isCustomerLoggedIn()): ?>

                <div class="row">
                    <div class="col-sm-6">
                        <div class="input-group input-group--wd">
                            <input type="text" name="author" class="input--full  required-entry" placeholder="<?php echo $name ?>" />
                            <span class="input-group__bar"></span>

                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="input-group input-group--wd">
                            <input type="text" name="email" class="input--full required-entry validate-email" placeholder="<?php echo $email ?>">
                            <span class="input-group__bar"></span>

                        </div>
                    </div>
                </div>
                <?php endif; ?>
                <div class="row">
                    <div class="col-md-12">
                        <div class="input-group input-group--wd">
                            <input type="text" name="url" class="input--full" placeholder="<?php echo $url ?>">
                            <span class="input-group__bar"></span>
                        </div>
                    </div>

                    <div class="col-md-12">
                        <div class="input-group input-group--wd">
                            <textarea class="textarea--full required-entry" name="comment"  placeholder="<?php echo $comment ?>"></textarea>
                            <span class="input-group__bar"></span>
                        </div>

                        <?php echo $this->getChildHtml('before_form_end') ?>

                        <?php if (!$this->customerMustLogin()): ?>


                            <button type="submit" class="btn btn--wd text-uppercase wave" value="Post your comment" id="post-the-comment"><?php echo $this->__('Leave a comment') ?></button>
                            <span class="please-wait" id="respond-please-wait" style="display:none;">
                                <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading next step...') ?>" title="<?php echo $this->__('Please wait...') ?>" class="v-middle" /> <?php echo $this->__('Please wait...') ?>
                            </span>

                        <?php endif; ?>

                    </div>
                </div>


        <?php endif; ?>
    </div>

    <?php if (!$this->customerMustLogin()): ?>
        <script type="text/javascript">
            //<![CDATA[
            new fishpig.WP.Comments.Form('respond', '<?php echo $this->getPost()->getPermalink() ?>');
            //]]>
        </script>
    <?php endif; ?>
</form>