<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $post = $this->getPost() ?>
<?php $comments = $this->getComments() ?>
<section class="content content--fill top-null" id="post-comments">
    <div class="container">
        <h2 class="text-uppercase text-center"><?php echo $this->__('Join the discussion') ?></h2>
       <div id="comments" class="comments-wrapper">
           <?php if ($comments->count() > 0): ?>
               <?php echo $this->getCommentsHtml() ?>
               <?php echo $this->getPagerHtml() ?>
           <?php endif; ?>
           <?php  echo $this->getFormHtml() ?>
        </div>


    </div>
</section>

