<div class="modal fade bs-example-modal-sm" role="dialog" id="modalAddToWishlist">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <button type="button" class="close icon-clear" data-dismiss="modal"></button>
            <div class="text-center">
                <div class="divider divider--xs"></div>
                <div class="loading">
                    <div class="divider divider--sm"></div>
                    <div class="loader">
                        <div class="bar"></div>
                        <div class="bar"></div>
                        <div class="bar"></div>
                        <div class="bar"></div>
                        <div class="bar"></div>
                    </div>
                </div>
                <p class="success"></p>
                <div class="divider divider--xs"> </div>
            </div>
        </div>
    </div>
</div>