<div class="modal fade bs-example-modal-sm" role="dialog" id="modalAddToCart">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <button type="button" class="close icon-clear" data-dismiss="modal"></button>
            <div class="text-center">
                <div class="divider divider--xs"></div>
                <p class="msg-success"></p>
                <div class="divider divider--xs"></div>
                <a href="<?php echo $this->getUrl('checkout/cart'); ?>" class="btn btn--wd  wishlist-hide"><?php echo $this->__('Go to Cart') ?></a>
                <div class="divider divider--xs wishlist-hide"></div>
            </div>
        </div>
    </div>
</div>