<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $posts = $this->getPosts() ?>
<?php if (count($posts) > 0): ?>

			<?php foreach($posts as $post): ?>
					<?php echo $this->getPostRenderer($post)->toHtml() ?>
			<?php endforeach; ?>

		<?php echo $this->getPagerHtml() ?>

<?php endif; ?>