<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 */
?>
<?php $post = $this->getPost() ?>
<?php if ($post): ?>

    <ul class="list-info">
        <li><span class="icon icon-clock"></span> Posted on <?php echo $post->getPostDate()?></li>
        <li class="post-author"><span class="icon flaticon-black302"></span> By <?php echo $post->getAuthor()->getDisplayName()?></li>
        <li class="post-category"><span class="icon flaticon-view9"></span> <?php echo $this->getCategoryString($post) ?></li>
        <?php if ($this->hasTags($post)): ?>
            <li class="post-tags"><span class="icon flaticon-tag43"></span> <?php echo $this->getTagString($post) ?></li>
        <?php endif; ?>

    </ul>

    <?php if ($this->canDisplayPreviousNextLinks()): ?>
            <section class="content content--parallax content--parallax--short top-null" data-image="images/parallax-bg-02.jpg">
                <div class="container">
                    <div class="blog-post-title blog-post-title--light">
                        <div class="post-navigation">
                            <?php if (($previous = $post->getPreviousPost()) !== false): ?>
                                <div class="pull-left"><a href="<?php echo $previous->getPermalink() ?>" class="button"
                                                          title="<?php echo $this->escapeHtml($previous->getPostTitle()) ?>"><?php echo $this->__('Previous Post') ?></a></div>
                            <?php endif; ?>
                            <?php if (($next = $post->getNextPost()) !== false): ?>
                                <div class="pull-right"><a href="<?php echo $next->getPermalink() ?>" class="button" title="<?php echo $this->escapeHtml($next->getPostTitle()) ?>"><?php echo $this->__('Next Post') ?> </a></div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </section>
    <?php endif; ?>

<?php endif; ?>