<script type="text/javascript">
    var data = "";
    var active = false;
    function insertParam(search, key, val) {
        var newParam = key + '=' + val,
            params = '?' + newParam;
        if (search) {
            params = search.replace(new RegExp('[\&]' + key + '[^&]*'), '&' + newParam);
            //params = search.replace(new RegExp('[\?&]' + key + '[^&]*'), '&' + newParam);
            if (params === search) {
                params += '&' + newParam;
            }
        }
        return params;
    }
    makeUrl = function (url) {
        if ($j('#leftCol').parent().hasClass('open')) {
            url=insertParam(url, 'filterOpened', '1');
        } else {
            url=insertParam(url, 'filterOpened', '0');
        }
        return url;
    }
    jQuery(function ($) {
        $('.ui-slider-handle').css('cursor', 'pointer');
        <?php if($this->ajaxLayered): ?>
        $('.block-layered-nav a').on('click', function (e) {
            if (!$(this).hasClass('toggle')) {
                var url = makeUrl($(this).attr('href'));
                sliderAjax(url);
            }
            e.preventDefault();
        });
        <?php endif; ?>

        <?php if($this->ajaxToolbar): ?>
        $('.filters-row select').removeAttr('onchange');
        $('.filters-row select').on('change', function (e) {
            var url = makeUrl($(this).attr('href'));
            sliderAjax(url);
            e.preventDefault();
        });
        $('.filters-row a:not(#showFilter,.filters-row__view)').on('click', function (e) {
            //var url = makeUrl($(this).attr('href'));
            var url = $(this).attr('href');
            if (url) sliderAjax(url);
            e.preventDefault();
        });
        <?php endif; ?>
    });


    <?php if($this->ajaxSlider || $this->ajaxLayered): ?>
    /*DONOT EDIT THIS CODE*/
    function sliderAjax(url) {
        if (!active) {
            active = true;
            jQuery(function ($) {
                oldUrl = url;

                try {
                    ajax_loading_on();
                    $.ajax({
                        url: url,
                        dataType: 'json',
                        type: 'post',
                        data: data,
                        success: function (data) {
                            if (data.productlist) {
                                $('.wd_product_list').empty();
                                $('.wd_product_list').replaceWith(data.productlist)
                            }
                            var hist = url.split('?');
                            if (window.history && window.history.pushState) {
                                window.history.pushState('GET', data.title, url);
                            }
                            <?php if($this->ajaxLayered): ?>
                            $('.block-layered-nav a').on('click', function (e) {
                                if (!$(this).hasClass('toggle')) {
                                    var url = makeUrl($(this).attr('href'));
                                    sliderAjax(url);
                                }
                                parent = $(this).parent();
                                if (parent.prop("tagName") == 'LABEL')  parent.prev().attr('checked', 'checked');
                                e.preventDefault();
                            });
                            <?php endif; ?>

                            <?php if($this->ajaxToolbar): ?>
                            $('.filters-row select').removeAttr('onchange');
                            $('.filters-row select').on('change', function (e) {
                                var url = makeUrl($(this).val());
                                sliderAjax(url);
                                e.preventDefault();
                            });
                            $('.filters-row a:not(#showFilter,.filters-row__view)').on('click', function (e) {
                                var url = makeUrl($(this).attr('href'));
                                if (url) sliderAjax(url);
                                e.preventDefault();
                            });
                            <?php endif; ?>

                            jQuery('#preloader .loader').fadeOut();
                            $('body').css('cursor', 'default');
                            $('.ui-slider-handle').css('cursor', 'pointer');

                            /*POSTPROCESS ISOTOP*/
                            if ($('.products-isotope').length) {
                                $('.products-isotope').imagesLoaded(function () {
                                    window.setTimeout(function () {
                                        $('.products-isotope').isotope({
                                            itemSelector: '.product-preview-wrapper',
                                            layoutMode: 'fitRows'
                                        });
                                    }, 500);

                                });
                            }
                            var minW = parseInt($('.products-col').find('.product-preview-wrapper:first-child').width());
                            if ($('.products-isotope').hasClass('two-in-row')) {
                                minW = minW - 200;
                            }
                            if ($('.products-col').parent().parent().hasClass('open')) {
                                $('.products-col').stop(true, false).animate({marginLeft: '280px'}, 200,
                                    function () {
                                        setProductSize($('.products-col'), minW);
                                        $('.products-isotope').isotope().isotope('layout');
                                    });
                            }
                            $('.filters-col__collapse__title').click(function (e) {
                                e.preventDefault;
                                $(this).parent('.filters-col__collapse').toggleClass('open');
                            })
                            ajax_loading_off();
                            filter_init();
                        }
                    })
                } catch (e) {
                }
            });
            active = false
        }
        return false
    }
    <?php endif; ?>
</script>