<?php $posts = $this->getPosts() ?>
<?php $theme=Mage::helper('welldone');?>
<?php if ((count($posts) > 0) && $theme->getLayoutOption('blog/recent_posts')): ?>
    <?php if($theme->getLayoutOption('blog/bg_landing')){
        $bg=Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'welldone/'.$theme->getLayoutOption('blog/bg_landing');
    }else
    {
        $bg=$this->getSkinUrl('images/theme/blog-bg.jpg');
    }
    ?>
    <section id="chapter3" class="content chapter">
        <div class="chapter__title title--white text-center">
            <div class="chapter__title__text">
                <?php if ($title = $this->getTitle()): ?>
                    <h2 class="text-uppercase"><?php echo $this->__($title) ?></h2>
                <?php endif; ?>
            </div>
        </div>
        <div class="chapter__content image-bg" data-image="<?php echo $bg ?>">
            <div class="blog-widget blog-widget--dark-color blog-widget--one-center">
                <?php foreach($posts as $post): ?>
                    <?php $post_date = $post->getPostDate();?>
                    <div class="blog-widget__item">
                        <div class="blog-widget__item__image-cell landing_blog pull-left <?php if(!$theme->getLayoutOption('blog/circle_images')):?>non-circle<?php endif;?>">
                                <?php if ($featuredImage = $post->getFeaturedImage()): ?>
                                    <div onclick="location.href='<?php echo $post->getPermalink() ?>'" style="background: url(<?php echo $featuredImage->getMediumImage() ?>) 50% 50% no-repeat;"></div>
                                <?php endif; ?>
                        </div>
                        <div class="blog-widget__item__offset-text pull-right">
                            <h3 class="blog-widget__item__offset-text__title text-uppercase"><?php echo $this->escapeHtml($post->getPostTitle()) ?></h3>
                            <?php if($theme->getLayoutOption('blog/date')):?>
                                <div class="blog-widget__item__offset-text__date"><span><?php echo date('jS F, Y', strtotime($post_date));?></span></div>
                            <?php endif; ?>
                            <div class="blog-widget__item__offset-text__teaser"><?php echo $post->getPostExcerpt();?> </div>
                            <?php if($theme->getLayoutOption('blog/readmore')):?>
                                <a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->htmlEscape($post->getPostTitle()) ?>" class="btn btn--wd"><?php echo $this->__('Read more') ?></a>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </section>
<?php endif; ?>